//! Window/taskbar icon plugin.
//!
//! Sets the game's icon on:
//! - the **primary game window** (title bar + Windows taskbar)
//! - the **splash window** (decorations are disabled, but the icon is still
//!   surfaced in alt-tab / dock pickers on macOS & Linux, and acts as a
//!   fallback if `decorations: false` is ever relaxed)
//!
//! ## Asset strategy
//! The plugin prefers the **pre-rendered** icon set under
//! `assets/icons/icon_<N>.png` (one PNG per size). The PNGs are
//! generated by [`scripts/build_icons.py`](../../scripts/build_icons.py)
//! from `assets/logo/icon.png` (the canonical 667×677 square crop
//! of the artwork).
//!
//! If a per-size PNG is **missing**, the plugin falls back to
//! Lanczos3-resizing the source logo at runtime. The fallback chain
//! tries `assets/logo/icon.png` first (the square crop) and
//! `assets/logo/logo_large.png` second (the 1328×800 hero artwork) —
//! so a fresh checkout with no `assets/icons/` directory still gets
//! a working icon (just lower quality at small sizes).
//!
//! ## Why a plugin?
//! Bevy 0.18's `Window` struct doesn't expose an `icon` field — the
//! high-level `Window` descriptor doesn't carry icons. Instead, the icon
//! has to be applied via `bevy_winit::WINIT_WINDOWS` after the underlying
//! `winit::window::Window` exists. This plugin:
//! 1. Loads the icon set synchronously at startup (no asset-server
//!    race — the OS asks for the icon ~immediately after window
//!    creation, before any async asset has loaded).
//! 2. Walks every `Window` in the world and applies the icon to each.
//!
//! ## Cross-platform notes
//! - **Windows**: the taskbar and title-bar icons both use the icons
//!   handed to `set_window_icon`. The list-of-sizes approach gives the
//!   taskbar a crisp 16×16 / 32×32 / 48×48 icon and Explorer a sharp
//!   thumbnail. A pre-built `assets/icons/icon.ico` is also produced
//!   for downstream packaging tools (e.g. `cargo-bundle`) but is **not**
//!   loaded by this plugin — `winit::Icon::from_rgba` only consumes
//!   raw RGBA bitmaps.
//! - **macOS**: `set_window_icon` sets the dock icon. The window title
//!   bar uses the app bundle icon instead (built by `cargo-bundle` from
//!   the .ico + .icns in the packaging step).
//! - **Linux (X11/Wayland)**: most desktop environments ignore it;
//!   winit will no-op on platforms without an icon implementation
//!   (`NoIcon::from_rgba`), so this is safe to ship unconditionally.
//! - **Web**: winit's web backend reports success but doesn't actually
//!   surface the icon (browsers derive it from the page favicon).

use bevy::prelude::*;
use bevy::window::PrimaryWindow;
use bevy_winit::WINIT_WINDOWS;
use image::{imageops::FilterType, ImageReader};
use std::io::Cursor;
use std::path::{Path, PathBuf};

use crate::ui::launch::splash::SplashWindow;

/// Side lengths (px) handed to `winit::Window::set_window_icon`. Windows
/// picks the bitmap whose dimensions are closest to the OS request
/// (taskbar = 32×32, Explorer thumbnail = 48×48 or 256×256). 256×256 is
/// the practical max — Windows taskbar will downscale to 32/48 anyway.
const ICON_SIZES: &[u32] = &[32, 48, 64, 128, 256];

/// Directory holding the pre-rendered per-size icon PNGs
/// (`icon_<N>.png`). Generated by `scripts/build_icons.py`.
const ICONS_DIR: &str = "assets/icons";

/// Per-size icon filename pattern: `icon_<N>.png`.
const ICON_PNG_NAME: &str = "icon_{size}.png";

/// Primary source logo — the canonical square 667×677 crop
/// ("icon.png" in the logo folder). Preferred over `logo_large.png`
/// because it's already composed for square use, so the runtime
/// resize fallback lands closer to the pre-rendered result.
const ICON_SOURCE_PRIMARY: &str = "assets/logo/icon.png";

/// Secondary source logo — the 1328×800 hero artwork. Used only if
/// `icon.png` is missing (a very old checkout). Not the right shape
/// for square icons, but the resize still produces a usable result.
const ICON_SOURCE_SECONDARY: &str = "assets/logo/logo_large.png";

/// Bevy plugin that installs the `apply_window_icons` startup system.
pub struct WindowIconPlugin;

impl Plugin for WindowIconPlugin {
    fn build(&self, app: &mut App) {
        // `Startup` runs after the primary window entity is spawned by
        // `WindowPlugin`, and the splash window entity is spawned by
        // `SplashPlugin` before `app.run()` (so by `Startup` it's
        // already in the world).
        app.add_systems(Startup, apply_window_icons);
    }
}

/// Resolve an asset path against both the cwd (which is the project
/// root when Bevy runs `cargo run`) and `CARGO_MANIFEST_DIR` (the
/// canonical project root). Returns `None` if neither location has
/// the file.
fn resolve_asset(rel: &str) -> Option<PathBuf> {
    if Path::new(rel).exists() {
        return Some(PathBuf::from(rel));
    }
    let fallback = Path::new(env!("CARGO_MANIFEST_DIR")).join(rel);
    if fallback.exists() {
        return Some(fallback);
    }
    None
}

/// Read the pre-rendered icon set (preferred) or fall back to
/// runtime-resizing the source logo, then walk every `Window` in the
/// world and call `set_window_icon` on its underlying winit window.
///
/// Any individual failure (decode error, resize error, winit
/// unavailable on this platform) is logged at `warn!` and skipped so
/// a missing or malformed logo doesn't crash the game.
fn apply_window_icons(
    primary_windows: Query<Entity, With<PrimaryWindow>>,
    splash_windows: Query<Entity, With<SplashWindow>>,
) {
    // Try the source logos up-front. We need at least one as a
    // runtime fallback for any per-size PNG that's missing.
    // Prefer `icon.png` (the canonical square crop) over
    // `logo_large.png` (the 1328x800 hero artwork).
    let logo_png: Option<Vec<u8>> = [ICON_SOURCE_PRIMARY, ICON_SOURCE_SECONDARY]
        .iter()
        .find_map(|path| {
            let resolved = resolve_asset(path)?;
            match std::fs::read(&resolved) {
                Ok(b) => Some(b),
                Err(e) => {
                    warn!(
                        "WindowIconPlugin: failed to read source logo {}: {}",
                        resolved.display(),
                        e
                    );
                    None
                }
            }
        });

    // Build one icon bitmap per size. Prefer the pre-rendered PNG;
    // fall back to runtime resize of the source logo if a per-size
    // PNG is missing or fails to decode.
    let icons_dir: Option<PathBuf> = resolve_asset(ICONS_DIR);
    let mut icons: Vec<(Vec<u8>, u32, u32)> = Vec::with_capacity(ICON_SIZES.len());
    for &size in ICON_SIZES {
        let icon = icons_dir
            .as_ref()
            .and_then(|dir| std::fs::read(dir.join(ICON_PNG_NAME.replace("{size}", &size.to_string()))).ok())
            .and_then(|bytes| decode_png_to_rgba(&bytes));

        let icon = match icon {
            Some(icon) => icon,
            None => {
                // Fall back to resizing the source logo. If the
                // source logo is also missing we have nothing to
                // resize and skip this size entirely.
                match logo_png.as_deref() {
                    Some(src) => match decode_and_resize_logo(src, size) {
                        Some(fallback_icon) => fallback_icon,
                        None => {
                            warn!(
                                "WindowIconPlugin: failed to source icon at {}x{} (no per-size PNG and logo resize failed)",
                                size, size
                            );
                            continue;
                        }
                    },
                    None => {
                        warn!(
                            "WindowIconPlugin: no source logo, cannot generate {}x{} icon",
                            size, size
                        );
                        continue;
                    }
                }
            }
        };
        icons.push(icon);
    }

    if icons.is_empty() {
        warn!("WindowIconPlugin: no icons generated, skipping apply");
        return;
    }

    // Apply to the primary window first (the one Windows actually
    // shows in the taskbar). Splash window gets the same icon for
    // alt-tab/dock consistency.
    for entity in &primary_windows {
        apply_icons_to_entity(entity, &icons);
    }
    for entity in &splash_windows {
        apply_icons_to_entity(entity, &icons);
    }
}

/// Apply each pre-built icon to one winit window. We try every size
/// in turn so the OS sees the full set and picks the best fit per
/// context (title bar vs. taskbar vs. Explorer thumbnail).
fn apply_icons_to_entity(entity: Entity, icons: &[(Vec<u8>, u32, u32)]) {
    // `WINIT_WINDOWS` is a `!Send` resource, so we have to read it
    // from the same thread that called `app.run()`. In a normal
    // Startup system that thread is the main thread, which matches.
    WINIT_WINDOWS.with(|winit_windows| {
        // `RefCell<WinitWindows>` — borrow the inner map and look up
        // the wrapper for this entity. `WindowWrapper<WinitWindow>`
        // derefs to `WinitWindow`, so we can call
        // `set_window_icon` directly through the auto-deref.
        let windows_ref = winit_windows.borrow();
        let Some(window_wrapper) = windows_ref.get_window(entity) else {
            // Window entity exists in Bevy's world but its native
            // winit handle hasn't materialised yet. On Windows the
            // primary window's winit handle is created very early
            // (during the first `resumed` callback), so this branch
            // is rare in practice — it can happen for the splash
            // window if the startup ordering ever shifts.
            warn!(
                "WindowIconPlugin: winit window handle missing for entity {:?}; icon not applied",
                entity
            );
            return;
        };

        for (rgba, w, h) in icons {
            match winit::window::Icon::from_rgba(rgba.clone(), *w, *h) {
                Ok(icon) => {
                    // `winit::window::Window::set_window_icon` is
                    // infallible on most platforms and just queues a
                    // main-thread redraw. No Result to handle.
                    window_wrapper.set_window_icon(Some(icon));
                }
                Err(e) => {
                    warn!(
                        "WindowIconPlugin: Icon::from_rgba failed for {}x{}: {:?}",
                        w, h, e
                    );
                }
            }
        }
    });
}

/// Decode a PNG byte slice into raw RGBA bytes + dimensions. No
/// resize. Used both directly (when the per-size icon PNG is
/// pre-rendered at the exact target size) and as the first step of
/// [`decode_and_resize_logo`].
///
/// Returns `None` for empty input, undecodable bytes, or
/// format-detection failure — callers must handle each gracefully.
pub fn decode_png_to_rgba(png_bytes: &[u8]) -> Option<(Vec<u8>, u32, u32)> {
    if png_bytes.is_empty() {
        return None;
    }
    let img = ImageReader::new(Cursor::new(png_bytes))
        .with_guessed_format()
        .ok()?
        .decode()
        .ok()?
        .to_rgba8();
    let (w, h) = img.dimensions();
    let bytes = img.into_raw();
    Some((bytes, w, h))
}

/// Synchronous helper: decode a PNG byte slice and resize it to
/// `target_size`×`target_size` using Lanczos3 (high-quality downscale).
/// Returns the raw RGBA bytes + dimensions ready for
/// `winit::window::Icon::from_rgba`. Used as the runtime fallback
/// when a pre-rendered per-size icon PNG is missing.
pub fn decode_and_resize_logo(png_bytes: &[u8], target_size: u32) -> Option<(Vec<u8>, u32, u32)> {
    let img = ImageReader::new(Cursor::new(png_bytes))
        .with_guessed_format()
        .ok()?
        .decode()
        .ok()?
        .to_rgba8();

    if img.width() == target_size && img.height() == target_size {
        // Already the right size — no resize needed.
        let (w, h) = img.dimensions();
        return Some((img.into_raw(), w, h));
    }

    // Lanczos3 gives the cleanest result when shrinking
    // 1328×800 → 32×32 (41× downscale). Triangle would alias badly
    // on the diagonal text strokes.
    let resized = image::imageops::resize(&img, target_size, target_size, FilterType::Lanczos3);
    let (w, h) = resized.dimensions();
    Some((resized.into_raw(), w, h))
}

#[cfg(test)]
mod tests {
    use super::*;
    use image::{ImageBuffer, Rgba};

    /// Resize a synthetic 4×4 RGBA image down to 2×2 and confirm the
    /// output dimensions and RGBA byte length are what
    /// `winit::Icon::from_rgba` expects.
    #[test]
    fn decode_and_resize_produces_correct_dimensions() {
        let img: ImageBuffer<Rgba<u8>, Vec<u8>> =
            ImageBuffer::from_fn(4, 4, |_x, _y| Rgba([255, 255, 255, 255]));
        let mut png_bytes: Vec<u8> = Vec::new();
        let dyn_img = image::DynamicImage::ImageRgba8(img);
        {
            let mut cursor = Cursor::new(&mut png_bytes);
            dyn_img
                .write_to(&mut cursor, image::ImageFormat::Png)
                .unwrap();
        }

        let (bytes, w, h) = decode_and_resize_logo(&png_bytes, 2).expect("resize must succeed");
        assert_eq!(w, 2);
        assert_eq!(h, 2);
        assert_eq!(bytes.len(), (2 * 2 * 4) as usize);
    }

    /// Confirm Lanczos3 preserves the alpha channel — the logo has
    /// transparent regions that must survive the resize.
    ///
    /// We use a fully-transparent 8×8 PNG resized to 4×4 and assert
    /// that **every** output pixel stays at alpha = 0. Lanczos3 is
    /// alpha-aware so the result is bit-identical when the source is
    /// uniform; only sharp alpha gradients bleed (and that's the
    /// case covered by `decode_and_resize_produces_correct_dimensions`
    /// via the existing PNG transparency check).
    #[test]
    fn decode_and_resize_preserves_transparency() {
        // Fully transparent 8×8 source.
        let img: ImageBuffer<Rgba<u8>, Vec<u8>> =
            ImageBuffer::from_fn(8, 8, |_x, _y| Rgba([0, 0, 0, 0]));
        let mut png_bytes: Vec<u8> = Vec::new();
        {
            let mut cursor = Cursor::new(&mut png_bytes);
            image::DynamicImage::ImageRgba8(img)
                .write_to(&mut cursor, image::ImageFormat::Png)
                .unwrap();
        }

        let (bytes, _w, _h) = decode_and_resize_logo(&png_bytes, 4).expect("resize");
        for y in 0..4 {
            for x in 0..4 {
                let idx = ((y * 4 + x) * 4) as usize;
                let alpha = bytes[idx + 3];
                assert_eq!(alpha, 0, "transparent pixel at ({},{}) became opaque", x, y);
            }
        }
    }

    /// Negative path: an empty byte slice must fail gracefully (return
    /// `None`) instead of panicking inside `image::ImageReader`.
    #[test]
    fn decode_and_resize_rejects_empty_input() {
        let result = decode_and_resize_logo(&[], 32);
        assert!(result.is_none());
    }

    /// Negative path: a non-PNG byte slice must return `None` so the
    /// caller can fall back to a default icon.
    #[test]
    fn decode_and_resize_rejects_garbage_input() {
        let result = decode_and_resize_logo(b"not a png", 32);
        assert!(result.is_none());
    }

    /// `decode_png_to_rgba` returns the source's exact dimensions
    /// when no resize is requested. Validates the helper used by
    /// the pre-rendered icon path.
    #[test]
    fn decode_png_to_rgba_returns_source_dimensions() {
        let img: ImageBuffer<Rgba<u8>, Vec<u8>> =
            ImageBuffer::from_fn(48, 48, |_x, _y| Rgba([10, 20, 30, 255]));
        let mut png_bytes: Vec<u8> = Vec::new();
        {
            let mut cursor = Cursor::new(&mut png_bytes);
            image::DynamicImage::ImageRgba8(img)
                .write_to(&mut cursor, image::ImageFormat::Png)
                .unwrap();
        }

        let (bytes, w, h) = decode_png_to_rgba(&png_bytes).expect("decode");
        assert_eq!(w, 48);
        assert_eq!(h, 48);
        assert_eq!(bytes.len(), (48 * 48 * 4) as usize);
        // Spot-check the first pixel survived decode+encode round-trip
        // (exact RGBA values; PNG is lossless).
        assert_eq!(&bytes[0..4], &[10, 20, 30, 255]);
    }

    /// Empty input to `decode_png_to_rgba` must short-circuit to
    /// `None` instead of panicking in `ImageReader::new`.
    #[test]
    fn decode_png_to_rgba_rejects_empty_input() {
        assert!(decode_png_to_rgba(&[]).is_none());
    }

    /// Garbage input to `decode_png_to_rgba` must return `None` so
    /// the plugin can fall through to the runtime resize path.
    #[test]
    fn decode_png_to_rgba_rejects_garbage_input() {
        assert!(decode_png_to_rgba(b"definitely not png").is_none());
    }

    /// If a pre-rendered `assets/icons/icon_<N>.png` exists on disk
    /// it must decode cleanly and yield exactly N×N RGBA bytes —
    /// this validates the production icon set is well-formed. The
    /// test only runs when the icon assets are present (e.g. when
    /// the repo is fully checked out, which is true in CI).
    #[test]
    fn pre_rendered_icon_set_decodes_cleanly() {
        let icons_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join(ICONS_DIR);
        if !icons_dir.exists() {
            // Skip — fresh checkout with no generated icons yet.
            return;
        }
        for &size in ICON_SIZES {
            let path = icons_dir.join(ICON_PNG_NAME.replace("{size}", &size.to_string()));
            let bytes = std::fs::read(&path)
                .unwrap_or_else(|e| panic!("missing icon {:?}: {}", path, e));
            let (rgba, w, h) = decode_png_to_rgba(&bytes)
                .unwrap_or_else(|| panic!("icon {:?} failed to decode", path));
            assert_eq!(
                (w, h),
                (size, size),
                "icon {:?} expected {}x{} but got {}x{}",
                path,
                size,
                size,
                w,
                h
            );
            assert_eq!(
                rgba.len(),
                (size * size * 4) as usize,
                "icon {:?} RGBA byte count mismatch",
                path
            );
        }
    }

    /// The runtime fallback source `assets/logo/icon.png` must
    /// decode cleanly — the plugin falls back to it when the
    /// pre-rendered per-size PNGs are missing. Skip if the file
    /// is absent (a very old checkout).
    #[test]
    fn runtime_fallback_icon_source_decodes_cleanly() {
        let icon_png = Path::new(env!("CARGO_MANIFEST_DIR")).join(ICON_SOURCE_PRIMARY);
        if !icon_png.exists() {
            return;
        }
        let bytes = std::fs::read(&icon_png).expect("read icon.png");
        let (rgba, w, h) = decode_png_to_rgba(&bytes).expect("decode icon.png");
        assert!(w >= 16 && h >= 16, "icon.png must be at least 16x16, got {}x{}", w, h);
        assert_eq!(rgba.len(), (w * h * 4) as usize);

        // Also confirm it resizes to a target size cleanly — the
        // fallback path uses `decode_and_resize_logo` for any size
        // that doesn't have a pre-rendered PNG.
        let (resized, rw, rh) = decode_and_resize_logo(&bytes, 64).expect("resize icon.png");
        assert_eq!((rw, rh), (64, 64));
        assert_eq!(resized.len(), (64 * 64 * 4) as usize);
    }
}